name: flora_seven
description: "FloraSeven - Smart Plant Monitoring System"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_riverpod: ^2.4.9
  # Networking
  dio: ^5.4.0
  http: ^1.2.1
  http_parser: ^4.0.2
  # Local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # UI components
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  fl_chart: ^0.65.0
  flutter_staggered_animations: ^1.1.1
  # Utilities
  logger: ^2.0.2+1
  intl: ^0.19.0
  uuid: ^4.3.3
  connectivity_plus: ^4.0.2
  url_launcher: ^6.2.2
  timezone: ^0.9.2
  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  # Notifications
  flutter_local_notifications: ^14.1.1
  # QR code scanning
  mobile_scanner: ^3.5.5
  # Service discovery
  multicast_dns: ^0.3.2
  # MQTT
  mqtt_client: ^9.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/FloraSevenAppLogo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/FloraSevenAppLogo.jpg"
